Update colab examples
huggingface/optimum-tpu pull request #86
Opened 2024-08-20 21:34 UTC by wenxindongwork

# Use transformers' AutoModelForCausalLM instead of optimum-tpu's  AutoModelForCausalLM for finetuning. 

The `from optimum.tpu` version imports models that are specifically optimized for inference. While the colab example works for smaller models, it fails with a HBM OOM error for llama3-70b (on a v4-256). Changing the following import statement solved the problem.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

2024-08-20 22:23 UTC, allenwang28 approved these changes

2024-08-21 07:58 UTC, tengomucho approved these changes
You are right @wenxindongwork, at some point I added some improvements for tuning, but with FSDP the models are essentially the same in `transformers` and in `optimum.tpu`, so it might well be easier just to import the `transformers` version.
Note that on the other hand, this means that the model might be loaded in `float32` and end up using more memory, whereas the `optimum.tpu`'s models will load on `bfloat16` by default. If you do this, you can end up with OOM on some configurations.

2024-08-21 08:00 UTC, tengomucho requested changes

2024-08-21 08:00 UTC, tengomucho commented on examples/language-modeling/llama_tuning.md
> +}
same comment here, I think it's simpler just to call `get_fsdp_training_args` for these supported models.

2024-08-21 16:00 UTC, wenxindongwork commented on examples/language-modeling/gemma_tuning.ipynb
> +    "}\n",
thanks for the quick review! `get_fsdp_training_args` accepts only the optimum.tpu model class, not the transformers one. I updated the `get_fsdp_training_args function`, so it should now work.

2024-08-21 16:59 UTC, tengomucho reviewed
Nice, with your change it looks fine. 🤗
Last question I was wondering was about using the `AutoModelForCausalLM` class from transformers rather than from optimum.tpu. 
AS I mentioned in a comment, in Optimum TPU models we set dtype to `bfloat16`, because TPU are capable of that and it uses less memory, e.g. [here](https://github.com/huggingface/optimum-tpu/blob/426d7be437ca367327114bc10f9badf1a0d1d056/optimum/tpu/modeling_llama.py#L1655). 
I hadn't test the scripts with float32, but if you do and it works fine please let me know, so we can just merge this.

2024-08-21 21:23 UTC, wenxindongwork commented
Just updated the examples to load the models in bf16 instead, hope that works!

2024-08-22 07:52 UTC, tengomucho approved these changes

2024-08-22 07:55 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-tpu/pr_86). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-22 08:00 UTC, tengomucho commented
The code style workflow is failing, can you run it locally (`make style`) and push again so we can merge this please?

2024-08-22 15:07 UTC, wenxindongwork commented
just installed ruff and ran make sytle. Thanks!

2024-08-22 15:08 UTC, tengomucho approved these changes

2024-08-22 15:37 UTC, merged